In [10]:
#Import packages
import pandas as pd
import numpy as np

In [6]:
#Read Data
data = pd.read_csv("CV_MaxFeatures.csv")
data

,abandonment,absence,absolute,absolutely,absorb,absorbed,absorbing,absorbs,abundance,abundant,...,yogurt,yorkshire,youth,youthful,z,za,zero,zone,zu,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,1,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
149,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150,0,0,0,2,0,0,0,0,3,1,...,0,0,0,0,0,0,0,2,0,0
151,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
152,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:

# Convert BoW matrix to Transaction Format
transactions = []

for _, row in data.iterrows():
    # Select column names where value is greater than 0 (present words)
    transaction = [col for col in data.columns if row[col] > 0] # Extract words present in document
    transactions.append(transaction)

In [24]:
transactions = pd.DataFrame(transactions)
transactions.to_csv("transactionData.csv",index = False)